### ISSUE TITLE
Documentation executor required

### ISSUE THREAD

**Issue by braghome** [spotify/trickle#14]
Their seems to some obvious lack executor service documention whereas guava docs do say that is allowed? I could not even find any trickle test that do take in executor service. Is that not required

**Comment by pettermahlen** [comment]
I'm not completely sure I understand the question, but the examples do show how to run using a separate executor: https://github.com/spotify/trickle/blob/master/src/examples/java/com/spotify/trickle/example/Examples.java#L165.

**Comment by braghome** [comment]
sorry I see that call to newSingleThreadExecutor
